###### NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays

In [1]:
!pip install numpy
import numpy as np

### space checking

In [ ]:
lst = range(1000)

In [ ]:
lst

range(0, 1000)

In [ ]:
import sys

In [ ]:
sys.getsizeof(4)*len(lst)

28000

In [ ]:
arr = np.arange(1000)

In [ ]:
arr.size*arr.itemsize

8000

### Fastness

In [ ]:
lst1 = range(1000000)
lst2 = range(1000000)

In [ ]:
import time

In [ ]:
start = time.time()
result = [(x+y) for x,y in zip(lst1,lst2)]
print((time.time()-start)*1000)

337.6340866088867


In [ ]:
arr1= np.arange(1000000)
arr2= np.arange(1000000)

In [ ]:
start = time.time()
result = arr1+arr2
print((time.time()-start)*1000)

10.779619216918945


#### Flexibilty

In [ ]:
arr1+arr2

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [ ]:
arr2*arr2

array([           0,            1,            4, ..., 999994000009,
       999996000004, 999998000001])

In [ ]:
lst = [1,2,3,3,3,3,3,3,3,3,3,3,3]

In [ ]:
lst+lst

[1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

In [ ]:
arr2/arr2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1., ...,  1.,  1.,  1.])

### creating a array

In [2]:
import numpy as np

In [3]:
x = [1,2,3,4,5]

In [4]:
type(x)

list

In [5]:
a = np.array(x)

In [6]:
type(a)

numpy.ndarray

In [7]:
a

array([1, 2, 3, 4, 5])

In [8]:
a.ndim

1

In [9]:
a = np.array([[2,3,4,5],[3,4,5,6]])

In [10]:
a

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [11]:
a.ndim

2

In [12]:
a = np.array([[2,3,4,5],[3,4,5,6],[3,4,5,5], [1,5,8,]])

<ipython-input-12-d21b2319c58c>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[2,3,4,5],[3,4,5,6],[3,4,5,5], [1,5,8,]])


In [13]:
a

array([list([2, 3, 4, 5]), list([3, 4, 5, 6]), list([3, 4, 5, 5]),
       list([1, 5, 8])], dtype=object)

In [ ]:
a.ndim

1

#### zeros and one's

In [14]:
var = np.zeros(5)

In [15]:
var

array([0., 0., 0., 0., 0.])

In [17]:
var = np.zeros((4,5,6))

In [18]:
var

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [19]:
var.ndim

3

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# functions

In [ ]:
var = np.array([22,33,44])

In [ ]:
var

array([22, 33, 44])

In [ ]:
type(var)

numpy.ndarray

In [ ]:
var.argmax()  # max value in index position

2

In [ ]:
var.argmin() # min index values

0

In [ ]:
var.data

In [ ]:
var.dtype

dtype('int64')

In [ ]:
var.dtype.name

'int64'

In [ ]:
var

array([22, 33, 44])

In [ ]:
var[1]

33

In [ ]:
var[0]

22

In [ ]:
var[0:2]

array([22, 33])

In [ ]:
var[0:3]

array([22, 33, 44])

In [ ]:
lst = [3,4,5]

In [ ]:
lst

[3, 4, 5]

In [ ]:
lst[1] = 444

In [ ]:
lst

[3, 444, 5]

In [ ]:
var

array([22, 33, 44])

In [ ]:
var[0] = 1000

In [ ]:
var

array([1000,   33,   44])

In [ ]:
arr = np.array([[1,2,3,4],[2,3,4,5]], dtype = complex)

In [ ]:
arr

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j]])

In [ ]:
# print an array with 10 values by giving max and min
aa = np.linspace(0,2,10)

In [ ]:
aa

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [ ]:
np.sin(aa)

array([0.        , 0.22039774, 0.42995636, 0.6183698 , 0.77637192,
       0.8961922 , 0.9719379 , 0.99988386, 0.9786557 , 0.90929743])

In [ ]:
np.tan(aa)

array([ 0.        ,  0.22595393,  0.47622143,  0.78684289,  1.23179859,
        2.01997033,  4.13172899, 65.60839711, -4.76215913, -2.18503986])

In [ ]:
np.tanh(aa)

array([0.        , 0.21863508, 0.41732165, 0.58278295, 0.7108445 ,
       0.8044548 , 0.87006166, 0.9146975 , 0.94445565, 0.96402758])

In [ ]:
from numpy import pi

In [ ]:
pi*aa

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [ ]:
0.21863508*pi

0.6868623611450168

#### reshape and resize

In [21]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
a.ndim

1

In [ ]:
import numpy as np

In [22]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
a.ndim

1

In [25]:
 b = a.reshape(5,4)
 b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [27]:
b.ndim

2

In [28]:
a.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [29]:
a.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [45]:
rnge = np.random.default_rng()

In [46]:
a = rnge.random((3,4))

In [47]:
a


array([[0.41067769, 0.20853126, 0.54301682, 0.68764139],
       [0.71686117, 0.05250152, 0.99264382, 0.37564751],
       [0.42486048, 0.7247601 , 0.78262304, 0.41839932]])

In [39]:
a.sum()

4.682684022737332

In [ ]:
a.sum(axis = 0)

array([1.13668203, 1.68448469, 1.56439248, 0.29712483])

In [ ]:
a.sum(axis = 1)

array([1.46624496, 1.57170875, 1.64473031])

In [ ]:
a.cumsum()

array([0.26161213, 0.56010328, 1.37432902, 1.46624496, 2.06634549,
       2.79490601, 2.98280709, 3.03795371, 3.31292308, 3.9703561 ,
       4.53262176, 4.68268402])

In [ ]:
a.cumprod()

array([2.61612134e-01, 7.80889051e-02, 6.35819966e-02, 5.84419912e-03,
       3.50710696e-03, 2.55513970e-03, 4.80113492e-04, 2.64766398e-05,
       7.28026491e-06, 4.78628651e-06, 2.69116456e-06, 4.03842244e-07])

In [ ]:
a = np.array([15, 18, 350, 100, 90, 150, 80, 60])

In [ ]:
np.argmax(a)

2

In [ ]:
a.max()

350

In [ ]:
np.argmax() and max()
np.argmin() and min()

In [ ]:
a.min()

0.05514662733306819

In [ ]:
q = 567890

In [ ]:
np.sqrt(q)

753.5847663003811

In [ ]:
x = [1,2,3,5,6]

In [ ]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.23606798, 2.44948974])

In [ ]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.60943791, 1.79175947])

In [ ]:
np.exp(x)

array([  2.71828183,   7.3890561 ,  20.08553692, 148.4131591 ,
       403.42879349])

In [ ]:
a

array([[0.26161213, 0.29849114, 0.81422574, 0.09191594],
       [0.60010053, 0.72856053, 0.18790107, 0.05514663],
       [0.27496937, 0.65743301, 0.56226566, 0.15006226]])

In [ ]:
a.shape

(3, 4)

### transpose

In [ ]:
aa = a.T

In [ ]:
aa.shape

(8,)

## reverse

In [ ]:
a

array([[0.26161213, 0.29849114, 0.81422574, 0.09191594],
       [0.60010053, 0.72856053, 0.18790107, 0.05514663],
       [0.27496937, 0.65743301, 0.56226566, 0.15006226]])

In [ ]:
aaa =  np.linspace(1,4,10)

In [ ]:
aaa

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [ ]:
aaa = np.array([[3,3,3],[4,4,4]])

In [ ]:
ax = aaa.sort(axis = 0)

In [ ]:
print(ax)

None


In [ ]:
aaa

array([[3, 3, 3],
       [4, 4, 4]])

In [ ]:
aaa[-1]

array([4, 4, 4])

In [ ]:
aaa[::-1]

array([[4, 4, 4],
       [3, 3, 3]])

In [ ]:
np.floor(4.4)

4.0

In [ ]:
np.ceil(5.5)

6.0

In [ ]:
np.abs(66.567890)

66.56789